# Generated by Django 5.0.7 on 2024-09-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('easy-big-wins', 'Easy Big Wins'), ('easy-small-wins', 'Easy Small Wins'), ('hard-big-wins', 'Hard Big Wins'), ('hard-small-wins', 'Hard Small Wins')], default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_links', to='bank.idea')),
            ],
        ),
    ]
