# Generated by Django 5.0.7 on 2024-08-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='complextity',
            new_name='complexity',
        ),
    ]
