# Generated by Django 5.0.7 on 2024-09-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_idea_notes_alter_idea_category_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='bank.idea'),
        ),
    ]
