# Generated by Django 5.0.7 on 2024-08-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_complextity_idea_complexity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='competitors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
