# Generated by Django 5.0.7 on 2024-09-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_link_idea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='idea',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
