# Generated by Django 5.0.7 on 2024-09-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='idea',
        ),
        migrations.AddField(
            model_name='idea',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='bank.label'),
        ),
    ]
