# Generated by Django 5.0.7 on 2024-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_customuser_is_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
