# Generated by Django 5.0.7 on 2024-10-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_clauderesponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
